apiVersion: v1
kind: Service
metadata:
  name: backend-spring-service
spec:
  selector: # 여기 selector 는 deployment 에 대한 selector 인가 pod 에 대한 selector 인가?
    app: backend-spring
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-spring
spec:
  selector:
    matchLabels:
      app: backend-spring
  replicas: 2
  template:
    metadata:
      name: backend-spring
      labels:
        app: backend-spring
    spec:
      containers:
        - name: backend-spring
          image: backend-spring:0.0.1
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
